@url = http://localhost:3001

# Get all patients
GET {{url}}/api/patients HTTP/1.1

###

# Add patient
POST {{url}}/api/patients HTTP/1.1
content-type: application/json

{
  "name": "Test",
  "dateOfBirth": "2011-11-11",
  "gender": "male",
  "occupation": "tester"
}