@url = http://localhost:3001
@patientId = d2773336-f723-11e9-8f0b-362b9e155667

# Get all patients
GET {{url}}/api/patients HTTP/1.1

###

# Get one patients
GET {{url}}/api/patients/{{patientId}} HTTP/1.1

###

# Add patient
POST {{url}}/api/patients HTTP/1.1
content-type: application/json

{
  "name": "Test",
  "dateOfBirth": "2011-11-11",
  "gender": "male",
  "ssn": "1",
  "occupation": "tester"
}

###

# Add entry

POST {{url}}/api/patients/{{patientId}}/entries HTTP/1.1
content-type: application/json

{
  "date": "2019-10-20",
  "specialist": "MD Test",
  "type": "HealthCheck",
  "description": "Test",
  "healthCheckRating": 1
}