@url = http://localhost:3001
#@url = https://throbbing-wood-7776.fly.dev

# Get All persons
GET {{url}}/api/persons HTTP/1.1

###
# Get one person
GET {{url}}/api/persons/1 HTTP/1.1

###
# Delete person
DELETE {{url}}/api/persons/2 HTTP/1.1

###
# Add person
POST {{url}}/api/persons/ HTTP/1.1
content-type: application/json

{
    "name": "test2",
    "number": 123
}

###
# Update person
PUT {{url}}/api/persons/633443d5225ebceb4debf975 HTTP/1.1
content-type: application/json

{
    "name": "test",
    "number": 123
}