# Get All persons
GET http://localhost:3001/api/persons HTTP/1.1

###
# Get one person
GET http://localhost:3001/api/persons/1 HTTP/1.1

###
# Delete person
DELETE http://localhost:3001/api/persons/2 HTTP/1.1

###
# Add person
POST http://localhost:3001/api/persons/ HTTP/1.1
content-type: application/json

{
    "name": "test2",
    "number": 123
}